add pylint-exit

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -18,7 +18,12 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install pylint
+        pip install pylint-exit
         pip install -r requirements.txt
     - name: Analysing the code with pylint
       run: |
-        pylint $(find . -name "*.py" | xargs) --disable=W0612,C0103,R0201,I1101,C0415
+        pylint $(find . -name "*.py" | xargs) --disable=W0612,C0103,R0201,I1101,C0415 || pylint-exit $?
+        if [ $? -ne 0 ]; then
+          echo "An error occurred while running pylint." >&2
+          exit 1
+        fi
